# Site settings
title: Linear Digression
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/polar-bear-theme" # the subpath of your site, e.g. /blog/
url: "http://mukulkhanna.github.io" # the base hostname & protocol for your site
twitter_username: mkulkhanna
github_username: mukulkhanna

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
